# Generated by Django 4.1.3 on 2023-01-18 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_catagory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="catagory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="store.category"
            ),
        ),
    ]
