# Generated by Django 4.1.3 on 2023-01-18 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_description"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="catagory",),
    ]
