# Generated by Django 4.1.3 on 2023-01-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
